buildscript {
    dependencies {
        classpath "com.android.tools.build:gradle:$androidPluginVersion"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    namespace 'com.viseven.develop.playercore'

    defaultConfig {
        compileSdk 34
        minSdkVersion 24
        targetSdkVersion 34

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    }
    buildTypes {
        release {
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            consumerProguardFiles 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    lint {
        abortOnError false
    }
    sourceSets.main {
        jniLibs.srcDir "src/main/libs"
        jni.srcDirs = [] // Disable the automatic ndk-build call by Android Studio.
    }
}

repositories {
    google()
    mavenCentral()
}

dependencies {
    api "androidx.media3:media3-common:$media3Version"
    api "androidx.media3:media3-session:$media3Version"
    api "androidx.media3:media3-exoplayer:$media3Version"

    implementation "androidx.annotation:annotation:$androidx_annotation"
    implementation "androidx.appcompat:appcompat:$app_compat"
    implementation "javax.inject:javax.inject:$javax_inject"
    implementation "com.annimon:stream:$annimon_stream"
    compileOnly "org.checkerframework:checker-qual:$qual"
}